// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGtDbZjre3mWGwcnJP8h8q_M4orDgOjhc',
    appId: '1:547993050771:web:466a4df4efdd7acbcd3766',
    messagingSenderId: '547993050771',
    projectId: 'igentech-13de9',
    authDomain: 'igentech-13de9.firebaseapp.com',
    storageBucket: 'igentech-13de9.appspot.com',
    measurementId: 'G-R5EH01ETF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJj2q6dkvOkExQzrTdXsSCBpqlV0_xikA',
    appId: '1:547993050771:android:7eedab5d38d9b214cd3766',
    messagingSenderId: '547993050771',
    projectId: 'igentech-13de9',
    storageBucket: 'igentech-13de9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB798_Ml-u7L_GN9MzxOY4Nm2gmSYVlEec',
    appId: '1:547993050771:ios:1b5609c3d5ca5b62cd3766',
    messagingSenderId: '547993050771',
    projectId: 'igentech-13de9',
    storageBucket: 'igentech-13de9.appspot.com',
    iosBundleId: 'com.example.template',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB798_Ml-u7L_GN9MzxOY4Nm2gmSYVlEec',
    appId: '1:547993050771:ios:a901a03aba2e7707cd3766',
    messagingSenderId: '547993050771',
    projectId: 'igentech-13de9',
    storageBucket: 'igentech-13de9.appspot.com',
    iosBundleId: 'com.example.template.RunnerTests',
  );
}
