name: theme_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  barcode_widget: ^2.0.1
  bloc: ^8.1.2
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.3
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.7
  go_router: ^13.0.1
  google_sign_in: ^6.2.1
  intl: ^0.18.1
  modal_progress_hud_nsn: ^0.5.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/
flutter_intl:
  enabled: true
