name: theme_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter_localizations:
        sdk: flutter
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localization: ^0.2.0
  get_it: ^7.6.7
  go_router: ^13.0.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/
flutter_intl:
  enabled: true
